name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish with Hatch
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/citekick
    permissions:
      id-token: write # Required for PyPI OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Hatch
        run: python -m pip install --upgrade hatch

      - name: Build package artifacts
        run: hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
